rgname                 = "dev-rg"
location               = "South Africa North"
service_principal_name = "dev-spn"
keyvault_name          = "devkeyvaultx"
aks_name               = "testaks"
vnet_name              = "aks-vnet"
vnet_address_space     = ["192.168.0.0/16"]
aks_subnet_name        = "aks-subnet"
aks_subnet_prefix      = ["192.168.0.0/24"]
