rgname                 = "dev-rg"
location               = "South Africa North"
service_principal_name = "dev-spn"
keyvault_name          = "devkeyvaultx"
aks_name               = "testaks"
vnet_name              = "aks-vnet"
aks_subnet_name        = "aks-subnet"
